# Generated by Django 3.1.2 on 2020-10-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('IdDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('IdEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('IdEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('ApPaterno', models.CharField(max_length=200)),
                ('ApMaterno', models.CharField(max_length=200)),
                ('FechaNac', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Genero', models.CharField(max_length=1, null=True)),
                ('TelCasa', models.IntegerField(null=True)),
                ('TelCell', models.IntegerField(null=True)),
                ('FechaIngreso', models.DateField()),
                ('IdDepartamentofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.departamento')),
                ('IdEmpresafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='IdEmpresaFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.empresa'),
        ),
    ]
